### ISSUE TITLE
failed assertions in Response.onEnd() don't throw all the way up

### ISSUE THREAD

**Issue by aoberoi** [commenthol/mock-http#5] opened 2015-11-23 08:01 UTC
it seems to me that if i have a failed assertion in `onEnd()` (which essentially is just throwing an error), then that error does not make it all the way up the call stack. its getting swallowed somewhere. my guess is that since Response is an EventEmitter, and `onEnd()` is invoked inside a handler, that when the handler throws, the EventEmitter doesn't do anything with that error (in order to stay loosely coupled).

**Comment by commenthol** [comment] 2020-07-10 05:33
Closing, as I could not reproduce this issue.

**Closed as completed by commenthol** 2020-07-10 05:33 UTC
