### ISSUE TITLE
request.headers not lower-cased

### ISSUE THREAD

**Issue by williamkapke** [commenthol/mock-http#2] opened 2015-04-14 23:10 UTC
When specifying `headers` on creation of a `Request` instance they are not lower-cased.

``` javascript
var http = require('mock-http');
var headers = { Authorization: 'Bearer 552d9922b59dd27b383d9674' };
var req = new http.Request({url:'/', method:'get', headers:headers});

console.log(req.getHeader('Authorization')); //undefined
console.log(req.headers['Authorization']); //Bearer 552d9922b59dd27b383d9674
```

...as a side note, maybe the method should be forced to upper-case too?

**Comment by commenthol** [comment] 2015-04-15 20:19
Thanks for highlighting. The issue is now fixed in v0.0.5. rawHeaders now contain the "input" (no conversion applied), while headers only contain lower-case keys as [stated](https://nodejs.org/api/http.html#http_message_headers).

**Closed as completed by commenthol** 2015-04-15 20:19 UTC
